language: node_js
node_js:
  - "0.10"
addons:
  hosts:
    - local.generatortest.com
before_install:
  - rvm use 1.9.3
  - gem install bundler
  - npm install -g bower
before_script:
  - echo "Running from ${PWD}"
  - echo "Install NPM dependencies"
  - npm install
  - echo "Mock test project"
  - "${PWD}/test/bin/mock"
  - echo "Provision server"
  - sudo "${PWD}/test/temp/bin/provision"
  - echo "Copy mock project to /vagrant for end-user tests"
  - sudo cp -R "${PWD}/test/temp" /vagrant
