---
- hosts:              webservers
  include:            ../bower_components/genesis-wordpress/provisioning/provision.yml

- hosts:              webservers
  gather_facts:       no
  tasks:
    - name:           Create /home/deploy/.ssh
      file:           path=/home/deploy/.ssh state=directory mode=0755 owner=deploy group=deploy
      sudo:           yes

    - name:           Copy deploy user's authorized_key
      authorized_key: user=deploy key="{{item}}"
      sudo:           yes
      with_file:
        - files/ssh/id_rsa.pub

    - name:           Copy deploy user's id_rsa
      copy:           src=files/ssh/id_rsa dest=/home/deploy/.ssh/id_rsa owner=deploy group=deploy mode=0600
      sudo:           yes

    - name:           Copy deploy user's id_rsa.pub
      copy:           src=files/ssh/id_rsa.pub dest=/home/deploy/.ssh/id_rsa.pub owner=deploy group=deploy mode=0600
      sudo:           yes
